import type { TranscriptSegment } from "../types/api";
import { extractYouTubeChapters, readYouTubeChapters } from "../integrations/youtube/chapters";
import { loadTranscriptRowsFromYouTubeUi } from "../integrations/youtube/transcriptDom";
import type {
  ContentErrorResponse,
  ContentRequest,
  ContentResponse,
  YouTubeTranscript,
  YouTubeTranscriptErrorCode,
  YouTubeVideoContext,
} from "../types/messages";

// Manifest content scripts execute as classic scripts. Keep runtime helpers local so Rollup
// cannot emit an ESM import that Chrome would reject for this entry point.
const VIDEO_ID_PATTERN = /^[A-Za-z0-9_-]{11}$/;
const YOUTUBE_HOSTS = new Set([
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "music.youtube.com",
  "youtu.be",
]);
const TRANSCRIPT_CACHE_LIMIT = 4;
const TRANSCRIPT_TIMEOUT_MS = 20_000;

interface CaptionTrack {
  baseUrl: string;
  isAutoGenerated: boolean;
  isDefault: boolean;
  languageCode: string;
}

interface CaptionRow {
  durationSec?: number;
  startSec: number;
  text: string;
}

interface ActiveTranscriptRequest {
  controller: AbortController;
  sequence: number;
  videoId: string;
}

class TranscriptExtractionError extends Error {
  constructor(
    readonly code: YouTubeTranscriptErrorCode,
    message: string,
    readonly retryable: boolean,
  ) {
    super(message);
    this.name = "TranscriptExtractionError";
  }
}

const transcriptCache = new Map<string, YouTubeTranscript>();
let activeTranscriptRequest: ActiveTranscriptRequest | null = null;
let transcriptRequestSequence = 0;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

function parseYouTubeVideoId(input: string): string | null {
  try {
    const url = new URL(input);
    if (!YOUTUBE_HOSTS.has(url.hostname.toLowerCase())) {
      return null;
    }
    const candidate =
      url.hostname.toLowerCase() === "youtu.be"
        ? url.pathname.split("/").filter(Boolean)[0]
        : url.pathname === "/watch"
          ? url.searchParams.get("v")
          : ["shorts", "embed", "live"].includes(url.pathname.split("/")[1] ?? "")
            ? url.pathname.split("/")[2]
            : null;
    return candidate && VIDEO_ID_PATTERN.test(candidate) ? candidate : null;
  } catch {
    return null;
  }
}

function isContentRequest(value: unknown): value is ContentRequest {
  if (!isRecord(value)) {
    return false;
  }
  if (value.type === "YALA_CONTENT_PING" || value.type === "YALA_GET_VIDEO_CONTEXT") {
    return true;
  }
  if (value.type === "YALA_GET_TRANSCRIPT") {
    return typeof value.videoId === "string" && VIDEO_ID_PATTERN.test(value.videoId);
  }
  return value.type === "YALA_SEEK_TO" && isFiniteNumber(value.seconds);
}

function textFrom(selectors: string[]): string {
  for (const selector of selectors) {
    const text = document.querySelector<HTMLElement>(selector)?.innerText.trim();
    if (text) {
      return text;
    }
  }
  return "";
}

function readVideoContext(): YouTubeVideoContext | null {
  const videoId = parseYouTubeVideoId(window.location.href);
  const player = document.querySelector<HTMLVideoElement>("video.html5-main-video, video");
  if (!videoId || !player) {
    return null;
  }

  const rawTitle = textFrom(["h1.ytd-watch-metadata yt-formatted-string", "h1.title"]);
  const documentTitle = document.title.replace(/\s*-\s*YouTube\s*$/, "").trim();
  return {
    channel:
      textFrom(["#owner #channel-name a", "ytd-channel-name a", "#upload-info #channel-name"]) ||
      "Kênh YouTube",
    currentTimeSec: Number.isFinite(player.currentTime) ? player.currentTime : 0,
    durationSec: Number.isFinite(player.duration) && player.duration > 0 ? player.duration : 0,
    language: document.documentElement.lang || "und",
    thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    title: rawTitle || documentTitle || "Video YouTube hiện tại",
    videoId,
  };
}

function normalizeCaptionText(value: string): string {
  return value
    .normalize("NFC")
    .replace(/[\u0000-\u001F\u007F\u200B-\u200D\uFEFF]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function toTranscriptSegments(rows: CaptionRow[], durationSec?: number): TranscriptSegment[] {
  const sortedRows = rows
    .filter((row) => Number.isFinite(row.startSec) && row.startSec >= 0)
    .sort((left, right) => left.startSec - right.startSec);
  const segments: TranscriptSegment[] = [];

  for (let index = 0; index < sortedRows.length && segments.length < 20_000; index += 1) {
    const row = sortedRows[index];
    const text = normalizeCaptionText(row.text);
    if (!text || (durationSec !== undefined && row.startSec > durationSec)) {
      continue;
    }

    const nextStart = sortedRows[index + 1]?.startSec;
    const inferredDuration =
      typeof nextStart === "number" && nextStart > row.startSec
        ? nextStart - row.startSec
        : 2;
    const requestedDuration =
      row.durationSec !== undefined && Number.isFinite(row.durationSec) && row.durationSec >= 0
        ? row.durationSec
        : inferredDuration;
    const unclampedEnd = row.startSec + requestedDuration;
    const endSec =
      durationSec !== undefined
        ? Math.max(row.startSec, Math.min(unclampedEnd, durationSec))
        : Math.max(row.startSec, unclampedEnd);

    segments.push({
      endSec,
      position: segments.length,
      startSec: row.startSec,
      text,
    });
  }

  return segments;
}

function extractBalancedJsonObject(source: string, startIndex: number): string | null {
  if (source[startIndex] !== "{") {
    return null;
  }

  let depth = 0;
  let escaped = false;
  let inString = false;
  for (let index = startIndex; index < source.length; index += 1) {
    const character = source[index];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === '"') {
        inString = false;
      }
      continue;
    }
    if (character === '"') {
      inString = true;
    } else if (character === "{") {
      depth += 1;
    } else if (character === "}") {
      depth -= 1;
      if (depth === 0) {
        return source.slice(startIndex, index + 1);
      }
    }
  }
  return null;
}

function captionTracksFromPlayerResponse(playerResponse: unknown): CaptionTrack[] {
  if (!isRecord(playerResponse) || !isRecord(playerResponse.captions)) {
    return [];
  }
  const renderer = playerResponse.captions.playerCaptionsTracklistRenderer;
  if (!isRecord(renderer) || !Array.isArray(renderer.captionTracks)) {
    return [];
  }

  const defaultTrackIndices = new Set<number>();
  if (Array.isArray(renderer.audioTracks)) {
    const defaultAudioTrackIndex =
      typeof renderer.defaultAudioTrackIndex === "number" ? renderer.defaultAudioTrackIndex : 0;
    const audioTrack = renderer.audioTracks[defaultAudioTrackIndex];
    if (isRecord(audioTrack)) {
      if (Array.isArray(audioTrack.captionTrackIndices)) {
        for (const value of audioTrack.captionTrackIndices) {
          if (typeof value === "number" && Number.isInteger(value)) {
            defaultTrackIndices.add(value);
          }
        }
      }
      if (typeof audioTrack.defaultCaptionTrackIndex === "number") {
        defaultTrackIndices.add(audioTrack.defaultCaptionTrackIndex);
      }
    }
  }

  const tracks: CaptionTrack[] = [];
  renderer.captionTracks.forEach((candidate, index) => {
    if (
      !isRecord(candidate) ||
      typeof candidate.baseUrl !== "string" ||
      typeof candidate.languageCode !== "string"
    ) {
      return;
    }
    try {
      const url = new URL(candidate.baseUrl);
      const hostname = url.hostname.toLowerCase();
      if (
        url.protocol !== "https:" ||
        (hostname !== "youtube.com" && !hostname.endsWith(".youtube.com"))
      ) {
        return;
      }
    } catch {
      return;
    }
    tracks.push({
      baseUrl: candidate.baseUrl,
      isAutoGenerated: candidate.kind === "asr",
      isDefault: candidate.isDefault === true || defaultTrackIndices.has(index),
      languageCode: candidate.languageCode.trim() || "und",
    });
  });
  return tracks;
}

function playerResponseMatchesVideo(playerResponse: unknown, videoId: string): boolean {
  if (!isRecord(playerResponse)) {
    return false;
  }
  if (
    isRecord(playerResponse.videoDetails) &&
    playerResponse.videoDetails.videoId === videoId
  ) {
    return true;
  }
  return captionTracksFromPlayerResponse(playerResponse).some((track) => {
    try {
      return new URL(track.baseUrl).searchParams.get("v") === videoId;
    } catch {
      return false;
    }
  });
}

function findPlayerResponseInText(source: string, videoId: string): Record<string, unknown> | null {
  const markerPattern = /(?:(?:window\s*\[\s*["']ytInitialPlayerResponse["']\s*\])|(?:["']?ytInitialPlayerResponse["']?))\s*[:=]\s*/g;
  while (markerPattern.exec(source) !== null) {
    const objectStart = source.indexOf("{", markerPattern.lastIndex);
    if (objectStart < 0 || objectStart - markerPattern.lastIndex > 16) {
      continue;
    }
    const serialized = extractBalancedJsonObject(source, objectStart);
    if (!serialized) {
      continue;
    }
    try {
      const parsed: unknown = JSON.parse(serialized);
      if (isRecord(parsed) && playerResponseMatchesVideo(parsed, videoId)) {
        return parsed;
      }
    } catch {
      // A page can contain stale or unrelated script fragments. Keep looking.
    }
  }
  return null;
}

function findPlayerResponseInDocument(videoId: string): Record<string, unknown> | null {
  for (const script of document.querySelectorAll<HTMLScriptElement>("script")) {
    const source = script.textContent;
    if (!source || !source.includes("ytInitialPlayerResponse")) {
      continue;
    }
    const playerResponse = findPlayerResponseInText(source, videoId);
    if (playerResponse) {
      return playerResponse;
    }
  }
  return null;
}

async function loadPlayerResponse(
  videoId: string,
  signal: AbortSignal,
): Promise<Record<string, unknown>> {
  const inlineResponse = findPlayerResponseInDocument(videoId);
  if (inlineResponse) {
    return inlineResponse;
  }

  const watchUrl = new URL("https://www.youtube.com/watch");
  watchUrl.searchParams.set("v", videoId);
  watchUrl.searchParams.set("hl", document.documentElement.lang || "en");

  let response: Response;
  try {
    response = await fetch(watchUrl, {
      credentials: "include",
      headers: { Accept: "text/html" },
      signal,
    });
  } catch (error) {
    if (isAbortError(error)) {
      throw error;
    }
    throw new TranscriptExtractionError(
      "NETWORK_ERROR",
      "Không thể tải thông tin phụ đề từ YouTube.",
      true,
    );
  }
  if (!response.ok) {
    throw new TranscriptExtractionError(
      "TRANSCRIPT_UNAVAILABLE",
      `YouTube không trả về thông tin phụ đề (HTTP ${response.status}).`,
      true,
    );
  }

  const html = await response.text();
  const playerResponse = findPlayerResponseInText(html, videoId);
  if (!playerResponse) {
    throw new TranscriptExtractionError(
      "TRANSCRIPT_UNAVAILABLE",
      "Không đọc được dữ liệu trình phát chứa thông tin phụ đề.",
      true,
    );
  }
  return playerResponse;
}

function readPlayerDuration(playerResponse: Record<string, unknown>): number | undefined {
  const player = document.querySelector<HTMLVideoElement>("video.html5-main-video, video");
  if (player && Number.isFinite(player.duration) && player.duration > 0) {
    return player.duration;
  }
  if (isRecord(playerResponse.videoDetails)) {
    const durationSec = Number(playerResponse.videoDetails.lengthSeconds);
    if (Number.isFinite(durationSec) && durationSec > 0) {
      return durationSec;
    }
  }
  return undefined;
}

function chooseCaptionTrack(tracks: CaptionTrack[]): CaptionTrack {
  const languagePreference = (document.documentElement.lang || navigator.language || "")
    .toLowerCase()
    .replace("_", "-");
  const primaryLanguage = languagePreference.split("-")[0];

  return [...tracks].sort((left, right) => {
    const score = (track: CaptionTrack): number => {
      const language = track.languageCode.toLowerCase().replace("_", "-");
      return (
        (track.isDefault ? 100 : 0) +
        (language === languagePreference ? 40 : 0) +
        (language.split("-")[0] === primaryLanguage ? 20 : 0) +
        (track.isAutoGenerated ? 0 : 10)
      );
    };
    return score(right) - score(left);
  })[0];
}

function parseJson3Rows(value: unknown): CaptionRow[] {
  if (!isRecord(value) || !Array.isArray(value.events)) {
    return [];
  }
  const rows: CaptionRow[] = [];
  for (const event of value.events) {
    if (!isRecord(event) || !isFiniteNumber(event.tStartMs) || !Array.isArray(event.segs)) {
      continue;
    }
    const text = event.segs
      .filter(isRecord)
      .map((segment) => (typeof segment.utf8 === "string" ? segment.utf8 : ""))
      .join("");
    rows.push({
      ...(isFiniteNumber(event.dDurationMs)
        ? { durationSec: Math.max(0, event.dDurationMs / 1000) }
        : {}),
      startSec: Math.max(0, event.tStartMs / 1000),
      text,
    });
  }
  return rows;
}

function parseXmlRows(source: string): CaptionRow[] {
  const documentNode = new DOMParser().parseFromString(source, "text/xml");
  if (documentNode.querySelector("parsererror")) {
    return [];
  }

  const rows: CaptionRow[] = [];
  for (const node of documentNode.querySelectorAll("text, p")) {
    const usesMilliseconds = node.tagName.toLowerCase() === "p";
    const rawStart = node.getAttribute(usesMilliseconds ? "t" : "start");
    const rawDuration = node.getAttribute(usesMilliseconds ? "d" : "dur");
    const start = Number(rawStart);
    const duration = rawDuration === null ? undefined : Number(rawDuration);
    if (!Number.isFinite(start)) {
      continue;
    }
    rows.push({
      ...(duration !== undefined && Number.isFinite(duration)
        ? { durationSec: Math.max(0, usesMilliseconds ? duration / 1000 : duration) }
        : {}),
      startSec: Math.max(0, usesMilliseconds ? start / 1000 : start),
      text: node.textContent ?? "",
    });
  }
  return rows;
}

async function loadCaptionSegments(
  track: CaptionTrack,
  durationSec: number | undefined,
  signal: AbortSignal,
): Promise<TranscriptSegment[]> {
  const captionUrl = new URL(track.baseUrl);
  captionUrl.searchParams.set("fmt", "json3");

  let response: Response;
  try {
    response = await fetch(captionUrl, {
      credentials: "include",
      headers: { Accept: "application/json, text/xml;q=0.9, */*;q=0.8" },
      signal,
    });
  } catch (error) {
    if (isAbortError(error)) {
      throw error;
    }
    throw new TranscriptExtractionError(
      "NETWORK_ERROR",
      "Không thể tải nội dung phụ đề từ YouTube.",
      true,
    );
  }
  if (!response.ok) {
    throw new TranscriptExtractionError(
      "TRANSCRIPT_UNAVAILABLE",
      `YouTube không trả về nội dung phụ đề (HTTP ${response.status}).`,
      true,
    );
  }

  const source = await response.text();
  if (!source.trim()) {
    throw new TranscriptExtractionError(
      "TRANSCRIPT_UNAVAILABLE",
      "YouTube trả về phụ đề trống. Liên kết phụ đề có thể đã hết hạn.",
      true,
    );
  }

  let rows: CaptionRow[] = [];
  try {
    const parsed: unknown = JSON.parse(source);
    rows = parseJson3Rows(parsed);
  } catch {
    rows = parseXmlRows(source);
  }
  const segments = toTranscriptSegments(rows, durationSec);
  if (segments.length === 0) {
    throw new TranscriptExtractionError(
      "INVALID_TRANSCRIPT",
      "Dữ liệu phụ đề không chứa đoạn nội dung hợp lệ.",
      true,
    );
  }
  return segments;
}

async function loadTranscriptFromYouTubeUi(signal: AbortSignal): Promise<TranscriptSegment[]> {
  const rows: CaptionRow[] = await loadTranscriptRowsFromYouTubeUi(signal);
  const player = document.querySelector<HTMLVideoElement>("video.html5-main-video, video");
  const durationSec =
    player && Number.isFinite(player.duration) && player.duration > 0 ? player.duration : undefined;
  return toTranscriptSegments(rows, durationSec);
}

async function extractTranscript(videoId: string, signal: AbortSignal): Promise<YouTubeTranscript> {
  let playerResponse: Record<string, unknown>;
  try {
    playerResponse = await loadPlayerResponse(videoId, signal);
  } catch (error) {
    const visibleSegments = await loadTranscriptFromYouTubeUi(signal);
    if (visibleSegments.length > 0) {
      return {
        chapters: readYouTubeChapters(),
        language: document.documentElement.lang || "und",
        segments: visibleSegments,
        videoId,
      };
    }
    throw error;
  }

  const durationSec = readPlayerDuration(playerResponse);
  const responseChapters = extractYouTubeChapters(playerResponse, durationSec);
  const chapters = responseChapters.length > 0
    ? responseChapters
    : readYouTubeChapters(document, durationSec);
  const tracks = captionTracksFromPlayerResponse(playerResponse);
  if (tracks.length === 0) {
    const visibleSegments = await loadTranscriptFromYouTubeUi(signal);
    if (visibleSegments.length > 0) {
      return {
        chapters,
        language: document.documentElement.lang || "und",
        segments: visibleSegments,
        videoId,
      };
    }
    throw new TranscriptExtractionError(
      "NO_TRANSCRIPT",
      "Video này không có phụ đề hoặc phụ đề không được chủ video cung cấp.",
      false,
    );
  }

  const track = chooseCaptionTrack(tracks);
  try {
    return {
      chapters,
      language: track.languageCode,
      segments: await loadCaptionSegments(track, durationSec, signal),
      videoId,
    };
  } catch (error) {
    if (isAbortError(error)) {
      throw error;
    }
    const visibleSegments = await loadTranscriptFromYouTubeUi(signal);
    if (visibleSegments.length > 0) {
      return { chapters, language: track.languageCode, segments: visibleSegments, videoId };
    }
    throw error;
  }
}

function isAbortError(error: unknown): boolean {
  return (
    (typeof DOMException !== "undefined" && error instanceof DOMException && error.name === "AbortError") ||
    (error instanceof Error && error.name === "AbortError")
  );
}

function cloneTranscript(transcript: YouTubeTranscript): YouTubeTranscript {
  return {
    chapters: transcript.chapters?.map((chapter) => ({ ...chapter })) ?? [],
    language: transcript.language,
    segments: transcript.segments.map((segment) => ({ ...segment })),
    videoId: transcript.videoId,
  };
}

function cacheTranscript(transcript: YouTubeTranscript): void {
  transcriptCache.delete(transcript.videoId);
  transcriptCache.set(transcript.videoId, cloneTranscript(transcript));
  if (transcriptCache.size > TRANSCRIPT_CACHE_LIMIT) {
    const oldestVideoId = transcriptCache.keys().next().value as string | undefined;
    if (oldestVideoId) {
      transcriptCache.delete(oldestVideoId);
    }
  }
}

function refreshCachedChapters(transcript: YouTubeTranscript): YouTubeTranscript {
  const playerResponse = findPlayerResponseInDocument(transcript.videoId);
  const durationSec = playerResponse ? readPlayerDuration(playerResponse) : undefined;
  const candidates = [
    transcript.chapters ?? [],
    ...(playerResponse ? [extractYouTubeChapters(playerResponse, durationSec)] : []),
    readYouTubeChapters(document, durationSec),
  ];
  const chapters = candidates.reduce<NonNullable<YouTubeTranscript["chapters"]>>(
    (best, candidate) => candidate.length > best.length ? candidate : best,
    [],
  );
  if (chapters.length <= (transcript.chapters?.length ?? 0)) {
    return transcript;
  }
  const refreshed = { ...transcript, chapters };
  cacheTranscript(refreshed);
  return refreshed;
}

function errorResponse(
  error: YouTubeTranscriptErrorCode,
  message: string,
  retryable: boolean,
  videoId?: string,
): ContentErrorResponse {
  return {
    error,
    message,
    ok: false,
    retryable,
    ...(videoId ? { videoId } : {}),
  };
}

async function handleTranscriptRequest(expectedVideoId: string): Promise<ContentResponse> {
  const currentVideoId = parseYouTubeVideoId(window.location.href);
  if (!currentVideoId) {
    return errorResponse(
      window.location.hostname.endsWith("youtube.com") ? "NO_VIDEO" : "NOT_YOUTUBE",
      "Hãy mở một video YouTube rồi thử lại.",
      false,
    );
  }
  if (currentVideoId !== expectedVideoId) {
    return errorResponse(
      "STALE_VIDEO",
      "Video đã thay đổi trước khi bắt đầu tải phụ đề.",
      true,
      currentVideoId,
    );
  }

  const cached = transcriptCache.get(expectedVideoId);
  if (cached) {
    return {
      ok: true,
      transcript: cloneTranscript(refreshCachedChapters(cached)),
      type: "YALA_TRANSCRIPT",
    };
  }

  activeTranscriptRequest?.controller.abort();
  const request: ActiveTranscriptRequest = {
    controller: new AbortController(),
    sequence: ++transcriptRequestSequence,
    videoId: expectedVideoId,
  };
  activeTranscriptRequest = request;
  const timeoutId = window.setTimeout(() => request.controller.abort(), TRANSCRIPT_TIMEOUT_MS);

  try {
    const transcript = await extractTranscript(expectedVideoId, request.controller.signal);
    const latestVideoId = parseYouTubeVideoId(window.location.href);
    if (
      activeTranscriptRequest?.sequence !== request.sequence ||
      latestVideoId !== expectedVideoId
    ) {
      return errorResponse(
        "STALE_VIDEO",
        "Video đã thay đổi trong lúc tải phụ đề.",
        true,
        latestVideoId ?? undefined,
      );
    }
    cacheTranscript(transcript);
    return { ok: true, transcript: cloneTranscript(transcript), type: "YALA_TRANSCRIPT" };
  } catch (error) {
    const latestVideoId = parseYouTubeVideoId(window.location.href);
    if (
      activeTranscriptRequest?.sequence !== request.sequence ||
      latestVideoId !== expectedVideoId
    ) {
      return errorResponse(
        "STALE_VIDEO",
        "Video đã thay đổi trong lúc tải phụ đề.",
        true,
        latestVideoId ?? undefined,
      );
    }
    if (isAbortError(error)) {
      return errorResponse(
        "NETWORK_ERROR",
        "Quá thời gian chờ YouTube trả về phụ đề.",
        true,
        expectedVideoId,
      );
    }
    if (error instanceof TranscriptExtractionError) {
      return errorResponse(error.code, error.message, error.retryable, expectedVideoId);
    }
    return errorResponse(
      "TRANSCRIPT_UNAVAILABLE",
      error instanceof Error ? error.message : "Không thể đọc phụ đề của video.",
      true,
      expectedVideoId,
    );
  } finally {
    window.clearTimeout(timeoutId);
    if (activeTranscriptRequest?.sequence === request.sequence) {
      activeTranscriptRequest = null;
    }
  }
}

chrome.runtime.onMessage.addListener((message: unknown, _sender, sendResponse) => {
  if (!isContentRequest(message)) {
    return;
  }

  if (message.type === "YALA_GET_TRANSCRIPT") {
    void handleTranscriptRequest(message.videoId).then(sendResponse);
    return true;
  }

  let response: ContentResponse;
  if (message.type === "YALA_CONTENT_PING") {
    response = { ok: true, type: "YALA_CONTENT_READY", url: window.location.href };
  } else if (message.type === "YALA_GET_VIDEO_CONTEXT") {
    const video = readVideoContext();
    response = video
      ? { ok: true, type: "YALA_VIDEO_CONTEXT", video }
      : {
          ok: false,
          error: parseYouTubeVideoId(window.location.href) ? "NO_VIDEO" : "NOT_YOUTUBE",
        };
  } else {
    const player = document.querySelector<HTMLVideoElement>("video.html5-main-video, video");
    if (!Number.isFinite(message.seconds) || message.seconds < 0) {
      response = { ok: false, error: "INVALID_TIMESTAMP" };
    } else if (!player) {
      response = { ok: false, error: "NO_VIDEO" };
    } else {
      const upperBound =
        Number.isFinite(player.duration) && player.duration > 0
          ? player.duration
          : message.seconds;
      player.currentTime = Math.min(message.seconds, upperBound);
      response = { ok: true, type: "YALA_SEEKED", currentTimeSec: player.currentTime };
    }
  }
  sendResponse(response);
});

let lastVideoId = parseYouTubeVideoId(window.location.href);
let lastReportedTime = -1;

function sendRuntimeMessage(message: object): void {
  try {
    void chrome.runtime.sendMessage(message).catch(() => undefined);
  } catch {
    // A tab can retain an old content script after the extension is reloaded.
  }
}

function emitVideoChanged(videoId: string | null): void {
  sendRuntimeMessage({ type: "YALA_VIDEO_CHANGED", videoId });
}

function notifyVideoChange(force = false): void {
  const videoId = parseYouTubeVideoId(window.location.href);
  const changed = videoId !== lastVideoId;
  if (!force && !changed) {
    return;
  }
  if (changed && activeTranscriptRequest?.videoId !== videoId) {
    activeTranscriptRequest?.controller.abort();
  }
  lastVideoId = videoId;
  emitVideoChanged(videoId);
  if (changed && !force) {
    window.setTimeout(() => notifyVideoChange(true), 750);
  }
}

function notifyVideoTime(): void {
  const videoId = parseYouTubeVideoId(window.location.href);
  const player = document.querySelector<HTMLVideoElement>("video.html5-main-video, video");
  if (!videoId || !player || !Number.isFinite(player.currentTime)) {
    return;
  }

  const currentTimeSec = player.currentTime;
  if (Math.floor(currentTimeSec) === lastReportedTime) {
    return;
  }
  lastReportedTime = Math.floor(currentTimeSec);
  sendRuntimeMessage({
    type: "YALA_VIDEO_TIME_CHANGED",
    videoId,
    currentTimeSec,
    durationSec: Number.isFinite(player.duration) && player.duration > 0 ? player.duration : 0,
  });
}

const handleNavigationEvent = () => notifyVideoChange();
document.addEventListener("yt-navigate-finish", handleNavigationEvent);
window.addEventListener("popstate", handleNavigationEvent);
window.setInterval(notifyVideoTime, 500);

const titleElement = document.querySelector("title");
if (titleElement) {
  new MutationObserver(() => notifyVideoChange()).observe(titleElement, {
    childList: true,
    subtree: true,
  });
}
